version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist

    db:
        image: mysql:5.7
        container_name: travellist-db
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel-kf-fit-2d002s
            MYSQL_USER: test
            MYSQL_PASSWORD: 123123
            MYSQL_ROOT_PASSWORD: 123123
#        volumes:
#            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#        networks:
#            - travellist
        volumes:
            - db-data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8008:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
volumes:
    db-data: ~
